# Generated by Django 3.2.7 on 2021-09-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='pic',
        ),
    ]
